const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const FLOORS_DIR = path.join(ROOT, 'assets', 'sprites', 'floors');
const WALLS_DIR = path.join(ROOT, 'assets', 'sprites', 'walls');
const OUTPUT_DIR = path.join(ROOT, 'src', 'services', 'tent', 'generated');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'tentSurfaceAssetMap.ts');

function listPngKeys(dir) {
  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith('.png'))
    .map((entry) => path.basename(entry.name, '.png'))
    .sort((a, b) => a.localeCompare(b));
}

function buildRequireLine(key, relativePath) {
  return `  ${JSON.stringify(key)}: require(${JSON.stringify(relativePath)}),`;
}

const floorKeys = listPngKeys(FLOORS_DIR);
const wallKeys = listPngKeys(WALLS_DIR);

const lines = [
  "import type { ImageSourcePropType } from 'react-native';",
  '',
  '// Generated by scripts/generate_tent_surface_asset_map.js',
  '// Run `npm run generate:tent-surfaces` after adding or renaming PNGs.',
  'export const SURFACE_SHEET_ASSETS: Record<string, ImageSourcePropType> = {',
  ...floorKeys.map((key) => buildRequireLine(key, `../../../../assets/sprites/floors/${key}.png`)),
  ...wallKeys.map((key) => buildRequireLine(key, `../../../../assets/sprites/walls/${key}.png`)),
  '} as const;',
  '',
];

fs.mkdirSync(OUTPUT_DIR, { recursive: true });
fs.writeFileSync(OUTPUT_FILE, `${lines.join('\n')}\n`, 'utf8');

console.log(`Generated ${path.relative(ROOT, OUTPUT_FILE)} with ${floorKeys.length + wallKeys.length} assets.`);
